name: Build AP World

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: List Initial Files
        run: ls
      - name: Remove Excess Files
        run: |
          rm rf .github
          rm rf docs
          rm rf test
          rm rf .git
          rm rf .gitignore
      - name: List Remaining Files
        run: ls
      - name: Zip apworld
        run: zip -r pokemon_snap.apworld ./{{ github.event.repository.name }}
      - name: List Files With Zip
        run: ls
      - name: Attach apworld to release
        uses: softprops/action-gh-release@v3
        with:
          files: pokemon_snap.apworld