name: Build AP World

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Build
        working-directory: ..
        run: |
          mv ${{ github.event.repository.name }} pokemon_snap
          zip -r pokemon_snap.apworld pokemon_snap
          mv pokemon_snap ${{ github.event.repository.name }}
          mv pokemon_snap.apworld /${{ github.event.repository.name }}/
      - name: Attach apworld to release
        uses: softprops/action-gh-release@v3
        with:
          files: pokemon_snap.apworld